# effect positive
# from main import N_CLASSES
import os

# base_path = 'C:/Users/user/Desktop/data/sets/Child Skin Disease'
# base_path = 'C:/Users/user/Desktop/data/sets/Child Skin Disease'
# base_path = '../../datasets/Child Skin Disease'
base_path = '../../datasets/Child Skin Disease(part)'
dataset_path = os.path.join(base_path, 'Total_Dataset')


num_res = 256 
num_batch = 32
num_classes = 2

name_dict1 = {
    'acnescarintegrated' : 'Acne scar', # add 
    'depressedscar' : 'Acne scar', 
    'acquiredtuftedhemangioma' : 'Acquired tufted angioma', 
    'acquiredtuftedhamangioma' : 'Acquired tufted angioma', # add a and e
    'cyst' : 'Epidermal cyst', 
    'cystintegrated' : 'Epidermal cyst', # add
    'infantilehemangioma' : 'Hemangioma',
    'hemangiomaintegrated' : 'Hemangioma',
    'ilven': 'Inflammatory linear verrucous epidermal nevus'
}


name_dict = {
    'Acnescarintegrated' : ['Acne scar', 'acnescar'], # add 
    'depressedscar' : ['Acne scar', 'acnescar'], 
    'acquiredtuftedhemangioma' : ['Acquired tufted angioma', 'acquiredtuftedangioma'], 
    'acquiredtuftedhamangioma' : ['Acquired tufted angioma','acquiredtuftedangioma'], # add a and e
    'cyst' : ['Epidermal cyst', 'epidermalcyst'], 
    'cystintegrated' : ['Epidermal cyst', 'epidermalcyst'], # add
    'infantilehemangioma' : ['Hemangioma', 'hemangioma'],
    'hemangiomaintegrated' : ['Hemangioma', 'hemangioma'],
    'ilven': ['Inflammatory linear verrucous epidermal nevus', 'inflammatorylinearverrucousepidermalnevus']
}

# effect positi
infection_list = ['Abscess',
                'Cellulitis',
                'Chicken pox (varicella)',
                'Cutaneous larva migrans',
                'Eczema herpeticum',
                'Folliculitis',
                'Furuncle',
                'Green nail syndrome',
                'Herpes simplex infection',
                'Herpes zoster',
                'Impetigo',
                'Molluscum contagiosum',
                'Paronychia',
                'Staphylococcal scalded skin syndrome',
                'Tinea capitis',
                'Tinea corporis',
                'Tinea cruris',
                'Tinea faciale', 
                'Tinea manus',
                'Tinea pedis',
                'Verruca plana',
                'Viral exanthem',
                'Wart']

# infection_list = list((map(lambda x : x.lower().replace(' ', ''), infection_list)))


N_CLASSES = 2
# infection_list = list((map(lambda x : x.lower().replace(' ', ''), infection_list)))


class_list = [
"Abscess",
"Acanthosis nigricans",
"Acne",
"Acne neonatorum",
"Acne scar",
"Acquired bilateral nevus of Ota-like macules",
"Acquired tufted angioma",
"Actinic cheilitis",
"Actinic keratosis",
"Alopecia areata",
"Androgenetic alopecia",
"Anetoderma",
"Angioedema",
"Angiofibroma",
"Angiokeratoma",
"Angular cheilitis",
"Aplasia cutis, congenital",
"Atopic dermatitis",
"Basal Cell Carcinoma of skin",
"Beau's lines",
"Becker's nevus",
"Blue nevus",
"Bowen's disease",
"Bullous disease",
"Cafe-au-lait spot",
"Cellulitis",
"Cheilitis",
"Chicken pox (varicella)",
"Childhood granulomatous periorificial dermatitis",
"Condyloma acuminata",
"Confluent and reticulated papillomatosis",
"Congenital Hemangioma",
"Congenital melanocytic nevus",
"Congenital smooth muscle hamartoma",
"Contact dermatitis",
"Corn, Callus",
"Cutaneous larva migrans",
"Cutaneous lupus erythematosus",
"Cutis marmorata",
"Cutis marmorata telangiectatica congenita (CMTC)",
"Depressed scar",
"Dermal Melanocytic Hamartoma",
"Dermatofibroma",
"Dermatofibrosarcoma protuberans",
"Digital Mucous cyst",
"Disseminated superficial actinic porokeratosis",
"Drug eruption",
"Dyshidrotic eczema",
"Dysplastic nevus",
"Eccrine poroma",
"Eczema herpeticum",
"Epidermal cyst",
"Epidermal nevus",
"Erythema ab igne",
"Erythema annulare centrifugum",
"Erythema dyschromicum perstans",
"Erythema induratum",
"Erythema multiforme",
"Erythema nodosum",
"Exfoliative dermatitis",
"Extramammary Paget'S Disease",
"Female type baldness",
"Fixed drug eruption",
"Folliculitis",
"Fordyce's spot",
"Freckle",
"Furuncle",
"Gianotti-Crosti syndrome",
"Graft Versus Host Disease",
"Granuloma annulare",
"Green nail syndrome",
"Guttate psoriasis",
"Halo nevus",
"Hand eczema",
"Hand, foot and mouth disease",
"Hemangioma",
"Henoch-Schonlein purpura",
"Herpes simplex infection",
"Herpes zoster",
"Hidradenitis suppurativa",
"Ichthyosis",
"Idiopathic guttate hypomelanosis",
"Impetigo",
"Incontinentia pigmenti",
"Infantile hemangioma",
"Infantile seborrheic dermatitis",
"Inflammatory linear verrucous epidermal nevus",
"Ingrowing nail",
"Insect bites and stings",
"Juvenile xanthogranuloma",
"Kaposi's sarcoma",
"Keloid scar",
"Keratoacanthoma",
"Keratosis pilaris",
"Lentigo",
"Lichen amyloidosis",
"Lichen nitidus",
"Lichen planus",
"Lichen simplex chronicus",
"Lichen striatus",
"Linear scleroderma",
"Lipoma",
"Livedo reticularis",
"Livedoid vasculitis",
"Localized scleroderma",
"Lymphangioma",
"Mastocytoma",
"Melanocytic nevus",
"Melanoma",
"Melanonychia",
"Melasma",
"Miliaria",
"Milium",
"Molluscum contagiosum",
"Mongolian spot",
"Mucosal melanocytic macule",
"Mycosis fungoides",
"Necrobiosis lipoidica",
"Neurofibroma",
"Neurofibromatosis",
"Nevus anemicus",
"Nevus comedonicus",
"Nevus depigmentosus",
"nevus lipomatous superficialis",
"Nevus of Ota",
"Nevus sebaceus",
"Nevus spilus",
"Nummular eczema",
"Normal",
"Onychodystrophy",
"Onychogryphosis",
"Onycholysis",
"Onychomycosis",
"Oral mucocele",
"Paget's disease of skin",
"Palmoplantar keratoderma",
"Panniculitis ",
"Parapsoriasis",
"Paronychia",
"Partial unilateral lentiginosis",
"Perioral dermatitis",
"Pigmented purpuric dermatosis",
"Pilomatricoma",
"Pincer nail",
"Pitted keratolysis",
"Pityriasis alba",
"Pityriasis amiantacea",
"Pityriasis lichenoides",
"Pityriasis rosea",
"Pityriasis versicolor",
"Poikiloderma of civatte",
"Porokeratosis",
"Port-Wine stain",
"Postinflammatory hyperpigmentation",
"Postinflammatory hypopigmentation",
"Progressive macular hypomelanosis",
"Prurigo",
"Prurigo pigmentosa",
"Pseudoxanthoma elasticum",
"Psoriasis",
"Purpura",
"Pustular psoriasis",
"Pustulosis palmaris et plantaris",
"Pyoderma gangrenosum",
"Pyogenic granuloma",
"Riehl's melanosis",
"Rosacea",
"Sacrococcygeal dimple",
"Salmon patch",
"Scabies",
"Scar",
"Sebaceous hyperplasia",
"Seborrheic dermatitis",
"Seborrheic keratosis",
"Senile gluteal dermatosis",
"Senile purpura",
"Skin tag",
"Spider angioma",
"Squamous cell carcinoma of skin",
"Staphylococcal scalded skin syndrome",
"Steatocystoma multiplex",
"Striae distensae",
"Subungual hemorrhage",
"Syringoma",
"Telangiectasia",
"Tinea capitis",
"Tinea corporis",
"Tinea cruris",
"Tinea faciale",
"Tinea manus",
"Tinea pedis",
"Toxic epidermal necrolysis",
"Trichotillomania",
"Ulcer",
"Urticaria",
"Urticaria pigmentosa",
"Vascular malformation",
"Vasculitis",
"Venous lake",
"Verruca plana",
"Viral exanthem",
"Vitiligo",
"Wart",
"Xanthelasma",
"Xerotic eczema",
]


exception_list = [
    'Normal'
]
# class_list = list((map(lambda x : x.lower().replace(' ', ''), class_list)))


class_list_without_infection = [
# "Abscess",
"Acanthosis nigricans",
"Acne",
"Acne neonatorum",
"Acne scar",
"Acquired bilateral nevus of Ota-like macules",
"Acquired tufted angioma",
"Actinic cheilitis",
"Actinic keratosis",
"Alopecia areata",
"Androgenetic alopecia",
"Anetoderma",
"Angioedema",
"Angiofibroma",
"Angiokeratoma",
"Angular cheilitis",
"Aplasia cutis, congenital",
"Atopic dermatitis",
"Basal Cell Carcinoma of skin",
"Beau's lines",
"Becker's nevus",
"Blue nevus",
"Bowen's disease",
"Bullous disease",
"Cafe-au-lait spot",
# "Cellulitis",
"Cheilitis",
# "Chicken pox (varicella)",
"Childhood granulomatous periorificial dermatitis",
"Condyloma acuminata",
"Confluent and reticulated papillomatosis",
"Congenital Hemangioma",
"Congenital melanocytic nevus",
"Congenital smooth muscle hamartoma",
"Contact dermatitis",
"Corn, Callus",
# "Cutaneous larva migrans",
"Cutaneous lupus erythematosus",
"Cutis marmorata",
"Cutis marmorata telangiectatica congenita (CMTC)",
"Depressed scar",
"Dermal Melanocytic Hamartoma",
"Dermatofibroma",
"Dermatofibrosarcoma protuberans",
"Digital Mucous cyst",
"Disseminated superficial actinic porokeratosis",
"Drug eruption",
"Dyshidrotic eczema",
"Dysplastic nevus",
"Eccrine poroma",
# "Eczema herpeticum",
"Epidermal cyst",
"Epidermal nevus",
"Erythema ab igne",
"Erythema annulare centrifugum",
"Erythema dyschromicum perstans",
"Erythema induratum",
"Erythema multiforme",
"Erythema nodosum",
"Exfoliative dermatitis",
"Extramammary Paget'S Disease",
"Female type baldness",
"Fixed drug eruption",
# "Folliculitis",
"Fordyce's spot",
"Freckle",
# "Furuncle",
"Gianotti-Crosti syndrome",
"Graft Versus Host Disease",
"Granuloma annulare",
# "Green nail syndrome",
"Guttate psoriasis",
"Halo nevus",
"Hand eczema",
"Hand, foot and mouth disease",
"Hemangioma",
"Henoch-Schonlein purpura",
# "Herpes simplex infection",
# "Herpes zoster",
"Hidradenitis suppurativa",
"Ichthyosis",
"Idiopathic guttate hypomelanosis",
# "Impetigo",
"Incontinentia pigmenti",
"Infantile hemangioma",
"Infantile seborrheic dermatitis",
"Inflammatory linear verrucous epidermal nevus",
"Ingrowing nail",
"Insect bites and stings",
"Juvenile xanthogranuloma",
"Kaposi's sarcoma",
"Keloid scar",
"Keratoacanthoma",
"Keratosis pilaris",
"Lentigo",
"Lichen amyloidosis",
"Lichen nitidus",
"Lichen planus",
"Lichen simplex chronicus",
"Lichen striatus",
"Linear scleroderma",
"Lipoma",
"Livedo reticularis",
"Livedoid vasculitis",
"Localized scleroderma",
"Lymphangioma",
"Mastocytoma",
"Melanocytic nevus",
"Melanoma",
"Melanonychia",
"Melasma",
"Miliaria",
"Milium",
# "Molluscum contagiosum",
"Mongolian spot",
"Mucosal melanocytic macule",
"Mycosis fungoides",
"Necrobiosis lipoidica",
"Neurofibroma",
"Neurofibromatosis",
"Nevus anemicus",
"Nevus comedonicus",
"Nevus depigmentosus",
"nevus lipomatous superficialis",
"Nevus of Ota",
"Nevus sebaceus",
"Nevus spilus",
"Nummular eczema",
"Normal",
"Onychodystrophy",
"Onychogryphosis",
"Onycholysis",
"Onychomycosis",
"Oral mucocele",
"Paget's disease of skin",
"Palmoplantar keratoderma",
"Panniculitis ",
"Parapsoriasis",
# "Paronychia",
"Partial unilateral lentiginosis",
"Perioral dermatitis",
"Pigmented purpuric dermatosis",
"Pilomatricoma",
"Pincer nail",
"Pitted keratolysis",
"Pityriasis alba",
"Pityriasis amiantacea",
"Pityriasis lichenoides",
"Pityriasis rosea",
"Pityriasis versicolor",
"Poikiloderma of civatte",
"Porokeratosis",
"Port-Wine stain",
"Postinflammatory hyperpigmentation",
"Postinflammatory hypopigmentation",
"Progressive macular hypomelanosis",
"Prurigo",
"Prurigo pigmentosa",
"Pseudoxanthoma elasticum",
"Psoriasis",
"Purpura",
"Pustular psoriasis",
"Pustulosis palmaris et plantaris",
"Pyoderma gangrenosum",
"Pyogenic granuloma",
"Riehl's melanosis",
"Rosacea",
"Sacrococcygeal dimple",
"Salmon patch",
"Scabies",
"Scar",
"Sebaceous hyperplasia",
"Seborrheic dermatitis",
"Seborrheic keratosis",
"Senile gluteal dermatosis",
"Senile purpura",
"Skin tag",
"Spider angioma",
"Squamous cell carcinoma of skin",
# "Staphylococcal scalded skin syndrome",
"Steatocystoma multiplex",
"Striae distensae",
"Subungual hemorrhage",
"Syringoma",
"Telangiectasia",
# "Tinea capitis",
# "Tinea corporis",
#"Tinea cruris",
# "Tinea faciale",
# "Tinea manus",
# "Tinea pedis",
"Toxic epidermal necrolysis",
"Trichotillomania",
"Ulcer",
"Urticaria",
"Urticaria pigmentosa",
"Vascular malformation",
"Vasculitis",
"Venous lake",
# "Verruca plana",
# "Viral exanthem",
"Vitiligo",
# "Wart",
"Xanthelasma",
"Xerotic eczema",
]